"""Excel export helper using xlsxwriter for financial voucher general ledgers."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import xlsxwriter

from src.backend.services.template_engine import ColumnDef, TemplateEngine


def create_excel_ledger(vouchers: list[dict[str, Any]], output_path: str | Path) -> Path:
    """Export list of vouchers into a professionally formatted Excel workbook.

    Each voucher item matches the JSON format from frontends:
    {
        "voucherNo": "AP2605001",
        "date": "2026-05-12",
        "vendor": "Metro Electric",
        "gross": 10700.0,
        "companyTaxId": "0105559123456",
        "sellerTaxId": "0105566111111",
        "lines": [
            {"type": "Dr", "code": "5040", "label": "ค่าน้ำค่าไฟ", "amount": 10000.0},
            {"type": "Dr", "code": "1154", "label": "ภาษีซื้อ", "amount": 700.0},
            {"type": "Cr", "code": "2195", "label": "เจ้าหนี้การค้า", "amount": 10700.0}
        ]
    }
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    workbook = xlsxwriter.Workbook(str(path))
    worksheet = workbook.add_worksheet("General Ledger Vouchers")

    # Define color palette & formats (Classic Professional accounting look)
    header_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": "Segoe UI",
            "bg_color": "#1F4E78",  # Navy blue
            "font_color": "#FFFFFF",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
        }
    )

    cell_left = workbook.add_format(
        {
            "font_size": 10,
            "font_name": "Segoe UI",
            "align": "left",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )

    cell_right = workbook.add_format(
        {
            "font_size": 10,
            "font_name": "Segoe UI",
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )

    currency_format = workbook.add_format(
        {
            "font_size": 10,
            "font_name": "Segoe UI",
            "num_format": '#,##0.00;(#,##0.00);"-"',
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )

    total_label_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": "Segoe UI",
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
            "top": 1,
            "bottom": 6,  # Double accounting line of double-line border
        }
    )

    total_currency_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": "Segoe UI",
            "num_format": '#,##0.00;(#,##0.00);"-"',
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
            "top": 1,
            "bottom": 6,  # Double-line bottom border
        }
    )

    # Set column layouts and sizes
    worksheet.set_column("A:A", 15)  # Voucher No
    worksheet.set_column("B:B", 13)  # Date
    worksheet.set_column("C:C", 11)  # Book Code
    worksheet.set_column("D:D", 14)  # Account Code
    worksheet.set_column("E:E", 28)  # Account Name
    worksheet.set_column("F:G", 16)  # Debit / Credit
    worksheet.set_column("H:H", 40)  # Description
    worksheet.set_column("I:J", 18)  # Co Tax ID / Vendor Tax ID

    # Title block
    title_format = workbook.add_format(
        {"bold": True, "font_size": 16, "font_name": "Segoe UI", "font_color": "#1F4E78"}
    )
    worksheet.write("A1", "Pre-Accounting Ledger Import File", title_format)
    worksheet.write("A2", "Generated by AI Accounting Copilot Integration Plane")
    worksheet.set_row(0, 24)
    worksheet.set_row(1, 18)

    # Headers
    headers = [
        "Voucher No",
        "Date",
        "Book Code",
        "Account Code",
        "Account Name",
        "Debit (฿)",
        "Credit (฿)",
        "Line Description",
        "Company Tax ID",
        "Seller Tax ID",
    ]

    header_row = 4
    worksheet.set_row(header_row, 30)
    for col_idx, text in enumerate(headers):
        worksheet.write(header_row, col_idx, text, header_format)

    row_idx = 5
    for v in vouchers:
        vnode = v.get("voucherNo", "AP-UNKN")
        vdate = v.get("date", "")
        vbook = v.get("bookCode", "AP")
        vdesc = v.get("vendor", "")
        co_tax = v.get("companyTaxId", "")
        se_tax = v.get("sellerTaxId", "")

        for line in v.get("lines", []):
            worksheet.set_row(row_idx, 22)
            worksheet.write(row_idx, 0, vnode, cell_left)
            worksheet.write(row_idx, 1, vdate, cell_left)
            worksheet.write(row_idx, 2, vbook, cell_left)
            worksheet.write(row_idx, 3, line.get("code", ""), cell_left)
            worksheet.write(row_idx, 4, line.get("label", ""), cell_left)

            # Route debit/credit based on line type
            l_type = line.get("type", "Dr")
            amount = float(line.get("amount", 0.0))

            if l_type == "Dr":
                worksheet.write(row_idx, 5, amount, currency_format)
                worksheet.write(row_idx, 6, 0.0, currency_format)
            else:
                worksheet.write(row_idx, 5, 0.0, currency_format)
                worksheet.write(row_idx, 6, amount, currency_format)

            line_desc = f"{line.get('label', '')} - {vdesc}"
            worksheet.write(row_idx, 7, line_desc, cell_left)
            worksheet.write(row_idx, 8, co_tax, cell_left)
            worksheet.write(row_idx, 9, se_tax, cell_left)

            row_idx += 1

    # Format Summary Accounting Totals row
    worksheet.set_row(row_idx, 26)
    for col in range(5):
        worksheet.write(row_idx, col, "", total_label_format)
    worksheet.write(row_idx, 4, "Grand Totals", total_label_format)

    # Use actual Excel SUM formula
    start_row = 6  # 1-indexed formula row number 6
    end_row = row_idx  # 1-indexed formula row number
    worksheet.write_formula(
        row_idx, 5, f"=SUM(F{start_row}:F{end_row})", total_currency_format
    )
    worksheet.write_formula(
        row_idx, 6, f"=SUM(G{start_row}:G{end_row})", total_currency_format
    )

    for col in range(7, 10):
        worksheet.write(row_idx, col, "", total_label_format)

    workbook.close()
    return path


def _reformat_date_to_thai(iso_date: str) -> str:
    """Convert YYYY-MM-DD to DD/MM/YYYY. Pass through if already formatted."""
    if not iso_date:
        return ""
    parts = iso_date.split("-")
    if len(parts) == 3 and len(parts[0]) == 4:
        return f"{parts[2]}/{parts[1]}/{parts[0]}"
    return iso_date


# ── Purchase Tax Report — template engine plumbing ─────────────────────────

# Fixed column layout for the Thai Purchase Tax Report (รายงานภาษีซื้อ).
# Columns mirror the 19-column standard format; numeric columns use data_type="number"
# so tests can distinguish them from text columns.
_PTR_COLUMNS: list[ColumnDef] = [
    ColumnDef("row_sequence",  "ลำดับที่",              "string"),
    ColumnDef("inv_no",        "เลขที่เอกสาร",          "string"),
    ColumnDef("inv_date",      "วันที่ออก",             "string"),  # pre-formatted by preprocessor
    ColumnDef("reference",     "อ้างอิง",               "string"),
    ColumnDef("_empty",        "อ้างอิงจากระบบ",       "string"),
    ColumnDef("status",        "สถานะ",                "string"),
    ColumnDef("seller_name",   "ผู้ขาย/ผู้ให้บริการ",  "string"),
    ColumnDef("seller_tax",    "เลขที่ 13 หลัก",       "string"),
    ColumnDef("seller_branch", "สาขา",                 "string"),
    ColumnDef("category",      "ชื่อสินค้า/บริการ",    "string"),
    ColumnDef("description",   "คำอธิบาย",             "string"),
    ColumnDef("no_vat",        "ไม่มี VAT",             "number"),
    ColumnDef("vat_0",         "VAT 0%",               "number"),
    ColumnDef("vat_7",         "VAT 7%",               "number"),
    ColumnDef("vat_amt",       "ยอด VAT",              "number"),
    ColumnDef("total",         "ทั้งหมด",              "number"),
    ColumnDef("wht_amt",       "หัก ณ ที่จ่าย",        "number"),
    ColumnDef("net_payable",   "ต้องชำระ",             "number"),
    ColumnDef("_empty2",       "",                     "string"),
]

# Columns (0-indexed) that xlsxwriter must write as float + currency_fmt.
_PTR_CURRENCY_COLS = frozenset(range(11, 18))
# Columns that use center alignment.
_PTR_CENTER_COLS = frozenset([0, 2, 8])


def _preprocess_purchase_tax_doc(doc: dict[str, Any]) -> dict[str, Any]:
    """Compute VAT buckets and normalise field names for template engine rendering.

    VAT bucket rules (ac_1101_vat):
      no_vat — vatRate == 0 AND vatAmt == 0
      vat_0  — vatRate == 0 AND vatAmt > 0
      vat_7  — all other cases
    """
    net     = float(doc.get("netAmt") or 0)
    vat_rate = float(doc.get("vatRate") or 0)
    vat_amt = float(doc.get("vatAmt") or 0)
    wht_amt = float(doc.get("whtAmt") or 0)

    no_vat = vat_0 = vat_7 = 0.0
    if vat_rate == 0 and vat_amt == 0:
        no_vat = net
    elif vat_rate == 0 and vat_amt > 0:
        vat_0 = net
    else:
        vat_7 = net

    total       = net + vat_amt
    net_payable = total - wht_amt

    return {
        "inv_no":        doc.get("invNo", ""),
        "inv_date":      _reformat_date_to_thai(doc.get("invDate", "")),
        "reference":     doc.get("reference", ""),
        "status":        doc.get("status", "ลงบัญชีแล้ว"),
        "seller_name":   doc.get("sellerName", ""),
        "seller_tax":    doc.get("sellerTax", ""),
        "seller_branch": doc.get("sellerBranch", "00000"),
        "category":      doc.get("category", ""),
        "description":   doc.get("description", ""),
        "no_vat":        str(no_vat),
        "vat_0":         str(vat_0),
        "vat_7":         str(vat_7),
        "vat_amt":       str(vat_amt),
        "total":         str(total),
        "wht_amt":       str(wht_amt),
        "net_payable":   str(net_payable),
    }


def create_purchase_tax_report(
    documents: list[dict[str, Any]],
    output_path: str | Path,
    company_info: dict[str, Any],
    report_period: tuple[str, str],
) -> Path:
    """Export purchase tax report (รายงานภาษีซื้อ) matching the standard Thai format.

    Args:
        documents: List of document dicts with keys: invNo, invDate, sellerName,
            sellerTax, sellerBranch, netAmt, vatRate, vatAmt, whtAmt, category,
            description, reference.
        output_path: Destination .xlsx file path.
        company_info: Dict with keys: name, taxId, branch, branchName, address.
        report_period: Tuple of (start_date, end_date) in DD/MM/YYYY format.
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    workbook = xlsxwriter.Workbook(str(path))
    ws = workbook.add_worksheet("รายงานภาษีซื้อ")

    # ── Fonts & Formats ──────────────────────────────────────────────
    font = "TH SarabunPSK"

    title_fmt = workbook.add_format(
        {"bold": True, "font_size": 14, "font_name": font}
    )
    meta_fmt = workbook.add_format({"font_size": 12, "font_name": font})
    header_fmt = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": font,
            "bg_color": "#1F4E78",
            "font_color": "#FFFFFF",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
            "text_wrap": True,
        }
    )
    text_fmt = workbook.add_format(
        {
            "font_size": 11,
            "font_name": font,
            "align": "left",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )
    text_center_fmt = workbook.add_format(
        {
            "font_size": 11,
            "font_name": font,
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )
    currency_fmt = workbook.add_format(
        {
            "font_size": 11,
            "font_name": font,
            "num_format": '#,##0.00;(#,##0.00);"-"',
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )
    total_label_fmt = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": font,
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
            "top": 1,
            "bottom": 6,
        }
    )
    total_currency_fmt = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": font,
            "num_format": '#,##0.00;(#,##0.00);"-"',
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
            "top": 1,
            "bottom": 6,
        }
    )

    # ── Column widths (A-S) ──────────────────────────────────────────
    col_widths = [
        8, 20, 14, 14, 14, 14, 30, 16, 10,
        20, 35, 14, 14, 14, 14, 14, 14, 14, 10,
    ]
    for ci, w in enumerate(col_widths):
        ws.set_column(ci, ci, w)

    # ── Header block (rows 0-8) ──────────────────────────────────────
    period_start, period_end = report_period
    now_str = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    company_name = company_info.get("name", "")
    company_tax = company_info.get("taxId", "")
    branch_name = company_info.get("branchName", "สำนักงานใหญ่")
    branch_code = company_info.get("branch", "00000")
    address = company_info.get("address", "")

    ws.merge_range("A1:S1", "รายงานใบสั่งซื้อ", title_fmt)
    ws.write("A2", "ผู้ออกรายงาน:", meta_fmt)
    ws.write("A3", company_name, meta_fmt)
    ws.write("A4", f"เลขประจำตัวผู้เสียภาษี: {company_tax}", meta_fmt)
    ws.write("A5", f"{branch_name}, {branch_code}", meta_fmt)
    ws.write("A6", address, meta_fmt)
    ws.write("A7", now_str, meta_fmt)
    ws.write("A8", f"{period_start}-{period_end}", meta_fmt)
    ws.write("A9", "แสดงข้อมูลพื้นฐาน", meta_fmt)

    for r in range(9):
        ws.set_row(r, 18)

    # ── Column headers (row 11, 0-indexed) ───────────────────────────
    headers = [
        "ลำดับที่",
        "เลขที่เอกสาร",
        "วันที่ออก",
        "อ้างอิง",
        "อ้างอิงจากระบบ",
        "สถานะ",
        "ผู้ขาย/ผู้ให้บริการ",
        "เลขที่ 13 หลัก",
        "สาขา",
        "ชื่อสินค้า/บริการ",
        "คำอธิบาย",
        "ไม่มี VAT",
        "VAT 0%",
        "VAT 7%",
        "ยอด VAT",
        "ทั้งหมด",
        "หัก ณ ที่จ่าย",
        "ต้องชำระ",
        "",
    ]
    header_row = 11
    ws.set_row(header_row, 30)
    for ci, h in enumerate(headers):
        ws.write(header_row, ci, h, header_fmt)

    # ── Data rows (row 12+) — rendered via template engine ───────────────
    engine = TemplateEngine(_PTR_COLUMNS)
    records = [_preprocess_purchase_tax_doc(doc) for doc in documents]
    _headers_unused, rendered_rows = engine.render(records)

    row = 12
    for row_data in rendered_rows:
        ws.set_row(row, 22)
        for ci, cell in enumerate(row_data):
            if ci in _PTR_CURRENCY_COLS:
                try:
                    ws.write_number(row, ci, float(cell), currency_fmt)
                except ValueError:
                    ws.write(row, ci, 0.0, currency_fmt)
            elif ci in _PTR_CENTER_COLS:
                try:
                    ws.write_number(row, ci, int(cell), text_center_fmt)
                except ValueError:
                    ws.write(row, ci, cell, text_center_fmt)
            else:
                ws.write(row, ci, cell, text_fmt)
        row += 1

    # ── Summary row ──────────────────────────────────────────────────
    if documents:
        ws.set_row(row, 26)
        for ci in range(11):
            ws.write(row, ci, "", total_label_fmt)
        ws.write(row, 10, "รวมทั้งสิ้น", total_label_fmt)

        data_start = 13  # 1-indexed row number for first data row
        data_end = row    # 1-indexed row number for last data row
        for ci in range(11, 18):
            col_letter = chr(ord("A") + ci)
            ws.write_formula(
                row, ci,
                f"=SUM({col_letter}{data_start}:{col_letter}{data_end})",
                total_currency_fmt,
            )
        ws.write(row, 18, "", total_label_fmt)

    workbook.close()
    return path
