"""Excel export helper using xlsxwriter for financial voucher general ledgers."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import xlsxwriter


def create_excel_ledger(vouchers: list[dict[str, Any]], output_path: str | Path) -> Path:
    """Export list of vouchers into a professionally formatted Excel workbook.

    Each voucher item matches the JSON format from frontends:
    {
        "voucherNo": "AP2605001",
        "date": "2026-05-12",
        "vendor": "Metro Electric",
        "gross": 10700.0,
        "companyTaxId": "0105559123456",
        "sellerTaxId": "0105566111111",
        "lines": [
            {"type": "Dr", "code": "5040", "label": "ค่าน้ำค่าไฟ", "amount": 10000.0},
            {"type": "Dr", "code": "1154", "label": "ภาษีซื้อ", "amount": 700.0},
            {"type": "Cr", "code": "2195", "label": "เจ้าหนี้การค้า", "amount": 10700.0}
        ]
    }
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    workbook = xlsxwriter.Workbook(str(path))
    worksheet = workbook.add_worksheet("General Ledger Vouchers")

    # Define color palette & formats (Classic Professional accounting look)
    header_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": "Segoe UI",
            "bg_color": "#1F4E78",  # Navy blue
            "font_color": "#FFFFFF",
            "align": "center",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
        }
    )

    cell_left = workbook.add_format(
        {
            "font_size": 10,
            "font_name": "Segoe UI",
            "align": "left",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )

    cell_right = workbook.add_format(
        {
            "font_size": 10,
            "font_name": "Segoe UI",
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )

    currency_format = workbook.add_format(
        {
            "font_size": 10,
            "font_name": "Segoe UI",
            "num_format": '#,##0.00;(#,##0.00);"-"',
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#E0E0E0",
        }
    )

    total_label_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": "Segoe UI",
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
            "top": 1,
            "bottom": 6,  # Double accounting line of double-line border
        }
    )

    total_currency_format = workbook.add_format(
        {
            "bold": True,
            "font_size": 11,
            "font_name": "Segoe UI",
            "num_format": '#,##0.00;(#,##0.00);"-"',
            "align": "right",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#D9D9D9",
            "top": 1,
            "bottom": 6,  # Double-line bottom border
        }
    )

    # Set column layouts and sizes
    worksheet.set_column("A:A", 15)  # Voucher No
    worksheet.set_column("B:B", 13)  # Date
    worksheet.set_column("C:C", 11)  # Book Code
    worksheet.set_column("D:D", 14)  # Account Code
    worksheet.set_column("E:E", 28)  # Account Name
    worksheet.set_column("F:G", 16)  # Debit / Credit
    worksheet.set_column("H:H", 40)  # Description
    worksheet.set_column("I:J", 18)  # Co Tax ID / Vendor Tax ID

    # Title block
    title_format = workbook.add_format(
        {"bold": True, "font_size": 16, "font_name": "Segoe UI", "font_color": "#1F4E78"}
    )
    worksheet.write("A1", "Pre-Accounting Ledger Import File", title_format)
    worksheet.write("A2", "Generated by AI Accounting Copilot Integration Plane")
    worksheet.set_row(0, 24)
    worksheet.set_row(1, 18)

    # Headers
    headers = [
        "Voucher No",
        "Date",
        "Book Code",
        "Account Code",
        "Account Name",
        "Debit (฿)",
        "Credit (฿)",
        "Line Description",
        "Company Tax ID",
        "Seller Tax ID",
    ]

    header_row = 4
    worksheet.set_row(header_row, 30)
    for col_idx, text in enumerate(headers):
        worksheet.write(header_row, col_idx, text, header_format)

    row_idx = 5
    for v in vouchers:
        vnode = v.get("voucherNo", "AP-UNKN")
        vdate = v.get("date", "")
        vbook = v.get("bookCode", "AP")
        vdesc = v.get("vendor", "")
        co_tax = v.get("companyTaxId", "")
        se_tax = v.get("sellerTaxId", "")

        for line in v.get("lines", []):
            worksheet.set_row(row_idx, 22)
            worksheet.write(row_idx, 0, vnode, cell_left)
            worksheet.write(row_idx, 1, vdate, cell_left)
            worksheet.write(row_idx, 2, vbook, cell_left)
            worksheet.write(row_idx, 3, line.get("code", ""), cell_left)
            worksheet.write(row_idx, 4, line.get("label", ""), cell_left)

            # Route debit/credit based on line type
            l_type = line.get("type", "Dr")
            amount = float(line.get("amount", 0.0))

            if l_type == "Dr":
                worksheet.write(row_idx, 5, amount, currency_format)
                worksheet.write(row_idx, 6, 0.0, currency_format)
            else:
                worksheet.write(row_idx, 5, 0.0, currency_format)
                worksheet.write(row_idx, 6, amount, currency_format)

            line_desc = f"{line.get('label', '')} - {vdesc}"
            worksheet.write(row_idx, 7, line_desc, cell_left)
            worksheet.write(row_idx, 8, co_tax, cell_left)
            worksheet.write(row_idx, 9, se_tax, cell_left)

            row_idx += 1

    # Format Summary Accounting Totals row
    worksheet.set_row(row_idx, 26)
    for col in range(5):
        worksheet.write(row_idx, col, "", total_label_format)
    worksheet.write(row_idx, 4, "Grand Totals", total_label_format)

    # Use actual Excel SUM formula
    start_row = 6  # 1-indexed formula row number 6
    end_row = row_idx  # 1-indexed formula row number
    worksheet.write_formula(
        row_idx, 5, f"=SUM(F{start_row}:F{end_row})", total_currency_format
    )
    worksheet.write_formula(
        row_idx, 6, f"=SUM(G{start_row}:G{end_row})", total_currency_format
    )

    for col in range(7, 10):
        worksheet.write(row_idx, col, "", total_label_format)

    workbook.close()
    return path
